version: '3.8'

services:
  api:
    build: .
    develop:
      watch:
        # Sincroniza alterações de código em tempo real (mais rápido)
        - action: sync
          path: ./src  # Pasta do seu código local
          target: /app/src # Pasta correspondente dentro do container
        # Reconstrói a imagem se arquivos de dependência ou Dockerfile mudarem
        - action: rebuild
          path: ./pyproject.toml # Ou package.json, Dockerfile, etc.
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: python main.py

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: